server:
  port: 8082

logging:
  level:
    org.springframework.transaction: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

keencho:
  p6spy:
    start_package: com.keencho
    limit_stack_trace: 10