server:
  port: 8082

logging:
  level:
    org.springframework.transaction: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: 123qwe@@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

keencho:
  p6spy:
    start_package: com.keencho
    limit_stack_trace: 10