server:
  port: 9999

logging:
  level:
    org.springframework.transaction: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

keencho:
  p6spy:
    start_package: com.sycho.spring
    limit_stack_trace: 10
